version: '3.7'

services:
  web:
    build: .
    command: python /codeintry/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/codeintry
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:11
    environment: 
      - POSTGRES_DB=letsflyonthewebsky_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bismillah_19@pg
    volumes:
      - my_data:/var/lib/postgresql/data/

volumes:
  my_data: