# Generated by Django 3.0.8 on 2020-08-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'permissions': [('special_status', 'can create newsletter')]},
        ),
    ]
