# Generated by Django 3.0.8 on 2020-08-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_auto_20200807_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={},
        ),
    ]
