# Generated by Django 3.0.8 on 2020-08-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_auto_20200809_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'permissions': [('special_status', 'can read all newsletter')]},
        ),
    ]
